version: "3.8"
services:
  ringface-db:
    image: mongo
    container_name: ringface-db
    volumes:
      - ./mongodb/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=ringfacedb
    # ports:
    #   - 27017-27019:27017-27019
  
  ringface-connector:
    image: ringface/connector:${VERSION}
    container_name: ringface-connector
    volumes:
      - ./data:/data
      - ./oauth-authorization.json:/app/oauth-authorization.json
    environment: 
      - OAUTH_FILE=/app/oauth-authorization.json
      - DATA_DIR=/data
    # ports:
    #   - 5000:5000

  ringface-classifier:
    image: ringface/classifier:${VERSION}
    container_name: ringface-classifier
    volumes:
      - ./data:/data
    # ports:
    #   - 5001:5001
    environment: 
      - DATA_DIR=/data
      - PARALLELISM=4 # how many frames should be processed in parallel (CPU parallelism)
      - EACH_FRAME=2 # 2 means each second frame is processed
      - MAX_FRAMES=100 # dont process more than the first x frames of the video
      - STOP_AFTER_EMPTY_FRAMES=10 # stop when 10 subsequent frames had no face 
      - MIN_TRUMBNAIL_SIZE_IN_PX=100 # min face size to consider for training

  ringface-bff:
    image: ringface/bff:${VERSION}
    container_name: ringface-bff
    depends_on:
      - ringface-db
      - ringface-classifier
      - ringface-connector
    volumes:
      - ./data:/data
    # ports:
    #   - 3333:3333
    environment: 
      - DATA_DIR=/
      - MONGO_HOST=ringface-db
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - CONNECTOR_HOST=ringface-connector
      - CLASSIFIER_HOST=ringface-classifier
    #poll for new ring events
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.poll-ring-events.schedule: "@every 10m"
      ofelia.job-exec.poll-ring-events.command: "curl localhost:3333/api/poll-and-process/today"      

  ringface-nginx:
    image: ringface/nginx:${VERSION}
    container_name: ringface-nginx
    depends_on:
      - ringface-bff
    ports:
      - 4300:80

  # scheduling facitly
  ringface-scheduler:
    image: mcuadros/ofelia:latest
    container_name: ringface-scheduler
    depends_on:
      - ringface-bff
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    
  